QUES-B Update
handling projection file, no habitat lookup data required, user defined nodata. user defined window size, previous teci file handling.

error: executing fragstats, quotes issue